services:
  - type: web
    name: longevity-prototype
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    nodeVersion: 20.11.0
    envVars:
      - key: VITE_APP_PASSWORD
        sync: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html